<template>
  <div class="min-h-screen bg-gray-50 dark:bg-[#0a0a0a] font-sans text-gray-900 dark:text-white pb-20">
    <!-- Non-printable Admin Header -->
    <div class="bg-white dark:bg-[#141414] border-b border-gray-200 dark:border-[#1f1f1f] px-6 py-4 flex items-center justify-between shadow-sm print:hidden sticky top-0 z-50">
       <div class="flex items-center gap-3">
          <NuxtLink to="/" class="flex items-center gap-3">
            <div class="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shadow-[0_0_10px_rgba(37,99,235,0.3)]">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z"></path><path d="M12 8v8"></path><path d="M8 12h8"></path>
              </svg>
            </div>
            <span class="text-lg font-bold tracking-tight">TalkBridge Meet</span>
          </NuxtLink>
       </div>
       
       <div class="flex items-center gap-4">
           <button @click="copyTranscript" class="px-4 py-2 bg-gray-100 dark:bg-[#1f1f1f] hover:bg-gray-200 dark:hover:bg-gray-800 text-sm font-semibold rounded-lg transition-colors flex items-center gap-2">
               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
               {{ isCopied ? 'Copied!' : 'Copy Transcript' }}
           </button>
           <button @click="downloadPdf" class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-bold rounded-lg shadow-lg hover:shadow-blue-500/30 transition-all flex items-center gap-2">
               <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
               Download PDF
           </button>
           <NuxtLink to="/" class="ml-2 text-sm text-gray-500 hover:text-red-500 transition-colors">Close</NuxtLink>
       </div>
    </div>

    <!-- Printable Area -->
    <div id="print-area" class="max-w-4xl mx-auto mt-10 p-8 bg-white dark:bg-[#141414]/80 dark:border dark:border-[#1f1f1f] rounded-2xl shadow-xl print:shadow-none print:border-0 print:p-0 print:m-0 print:max-w-none">
       
       <div class="border-b border-gray-200 dark:border-gray-800 pb-6 mb-8 text-center sm:text-left flex flex-col sm:flex-row justify-between items-center print:flex-row print:justify-between">
           <div>
               <h1 class="text-3xl font-extrabold text-gray-900 dark:text-white mb-2">Meeting Transcript</h1>
               <p class="text-gray-500 dark:text-gray-400">Generated by TalkBridge</p>
           </div>
           <div class="mt-4 sm:mt-0 text-right">
               <div class="text-sm font-semibold text-gray-500 dark:text-gray-400">{{ currentDate }}</div>
               <div class="text-xs text-gray-400 mt-1">{{ transcripts.length }} messages logged</div>
           </div>
       </div>

       <div v-if="transcripts.length === 0" class="text-center py-20 text-gray-500 italic">
           No conversation data was recorded during this meeting.
       </div>

       <div v-else class="space-y-0 relative border-l-2 border-gray-100 dark:border-gray-800/60 ml-4 print:border-gray-300">
          <div v-for="(msg, index) in transcripts" :key="index" class="relative pl-8 py-4 border-b border-gray-100 dark:border-gray-800/40 last:border-0 print:border-gray-200 print:break-inside-avoid">
             <!-- Timeline dot -->
             <div class="absolute w-3 h-3 bg-blue-500 rounded-full left-[-7px] top-6 ring-4 ring-white dark:ring-[#141414] print:ring-white"></div>
             
             <div class="font-bold text-gray-900 dark:text-white mb-2 flex items-center gap-2">
                 <span>{{ msg.speakerName }}</span>
                 <span v-if="FLAGS[msg.speakerLanguage]" class="text-xs">{{ FLAGS[msg.speakerLanguage] }}</span>
             </div>
             
             <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                 <div class="bg-gray-50 dark:bg-[#0a0a0a] p-3 rounded-lg border border-gray-100 dark:border-[#1f1f1f] print:border-gray-300">
                     <div class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Original (Spoken)</div>
                     <p :dir="RTL_LANGS.includes(msg.speakerLanguage) ? 'rtl' : 'ltr'" class="text-sm text-gray-700 dark:text-gray-300 italic opacity-80">{{ msg.originalText }}</p>
                 </div>
                 
                 <div v-if="msg.translatedText && msg.translatedText !== msg.originalText" class="bg-blue-50 dark:bg-blue-900/10 p-3 rounded-lg border border-blue-100 dark:border-blue-900/30 print:border-gray-300">
                     <div class="text-[10px] font-bold text-blue-400 uppercase tracking-widest mb-1">Translated (Received)</div>
                     <p :dir="isProbablyRtl(msg.translatedText) ? 'rtl' : 'ltr'" class="text-[15px] font-medium text-gray-900 dark:text-white">{{ msg.translatedText }}</p>
                 </div>
             </div>
          </div>
       </div>

    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';

const transcripts = ref([]);
const isCopied = ref(false);
const currentDate = new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

const FLAGS = {
  'ar': '🇸🇦', 'en': '🇺🇸', 'fr': '🇫🇷', 'es': '🇪🇸', 'de': '🇩🇪',
  'zh': '🇨🇳', 'hi': '🇮🇳', 'pt': '🇧🇷', 'ru': '🇷🇺', 'tr': '🇹🇷'
};
const RTL_LANGS = ['ar', 'he', 'ur', 'fa'];

// Quick heuristic for checking if translated text is RTL 
// (because we don't have userTargetLang per message if we're a mixed host)
const isProbablyRtl = (text) => {
    if (!text) return false;
    const rtlRegex = /[\u0591-\u07FF\uFB1D-\uFDFD\uFE70-\uFEFC]/;
    return rtlRegex.test(text);
};

onMounted(() => {
    try {
        const stored = sessionStorage.getItem('talkbridge_summary');
        if (stored) {
            transcripts.value = JSON.parse(stored);
        }
    } catch (e) {
        console.error("Failed to load transcript summary", e);
    }
});

const downloadPdf = () => {
    window.print();
};

const copyTranscript = () => {
    if (!transcripts.value.length) return;
    
    let textOut = `Meeting Transcript - ${currentDate}\n\n`;
    transcripts.value.forEach(msg => {
        textOut += `[${msg.speakerName}]: ${msg.originalText}\n`;
        if (msg.translatedText && msg.translatedText !== msg.originalText) {
            textOut += `(Translation): ${msg.translatedText}\n`;
        }
        textOut += `\n`;
    });
    
    navigator.clipboard.writeText(textOut);
    isCopied.value = true;
    setTimeout(() => isCopied.value = false, 2000);
};
</script>

<style>
@media print {
  body {
    background: white !important;
    color: black !important;
  }
}
</style>
